language: node_js
node_js:
- '12'
dist: trusty
sudo: required
env:
  global:
    secure: wJSON7Ey0q6FPcAsRKZWWhIvqV8QmGoHt30DnL9OIxOBvX0jvoadoLJj/WJPlDdbb3Ib+x+Z4IHdypefKmHN2PU+30mn8nWbMCEjSHYdvyaT+q62Yn8eWg1C/okbxq+NF+4o2TnTv4SDLmJhEVCBK+PgTjnAJjp+qFOLCZ9fukLek4+HdSFAG3tKN9lrnGZ9mWgbc2HE3hT6pN7JmLXZSR7dPltoPzoNSXZZaQsuRY1TOgCPpb99000gzTbTOnE5t5Cyt6osCX3MWKslA3kYzUHkFv4SisBC4P4PbNEOFjPD9GBiWK1gF93xspjy8VpKb1T7XQENUeDcVqIyQzLsHt4jMa+91QdakPTz4Pu/+s6gwNUWmtA3qKCowO4ZHh7rO65iCJUii4H4X1YFjvJ60IdERBMT3Ftz6cWXXkHCHS9Sm+6sNE+SA4+e5WMR48q6llWW8SCLc18XUqWAvYQnLCYDJ1TWNBt7LwbYqJcjIVkG64mrXip2/E3AQIy3mwrF/Ec4shOWryzQGZRO6Kb/G3X2E9PTJkSi7+a6gqhy6J9W4Udbs3WNHkcRfRQL/IZKky+iao39rtE5HhMJhZae6TnLkxDHBx0ohBZhTj21791Lhi2roeGzARUKjEOlmf4sOaRsJbfXDpex6lPwnc4D092haydXHgV2mmYCaeEVlNM=
addons:
  chrome: stable
  sonarcloud:
    organization: jorgerambla
    token: "$SONAR_TOKEN"
before_script:
- npm install -g --silent @angular/cli@8.3.20
script:
- ng lint
- ./build.sh
