language: node_js
node_js:
- '12'
dist: trusty
sudo: required
addons:
  chrome: stable
  sonarcloud:
    organization: jorgerambla
    token:
      secure: "$SONAR_TOKEN"
before_script:
- npm install -g --silent @angular/cli@8.3.20
script:
- ng lint
- sonar-scanner
env:
  global:
    secure: 1fNPBOT04+fW3U3zmxVcRPI1AiCzhKopqK4uxWhQHPMpz6qSugwwKq1wpxH751q8VTRPAYmN+ZkuNfnsLQXjE0r7UdodOQiE2ShyKz1tCow8TCL6RsKqU8r5XT5/5x8OZGKVzWux9yIyFLrIMTMMCVLCYMxf1lTXUd6L3IuDrlNXXUj+TTyZHejhhbCcqjezum+/DvJ8z0DAcEZbLTFrkRNWmvPx6Fd8tlXqzhyM17mL9fFGgWfNReXRvkEx3EnS18plSsMqtd77Jdu2WP2x02F5rLf05INwNrIKquo7ZWzQ5jicqMj1GVtf02Z1ZS4UGMWj0IJkwzRMWOTUnP4JfaI4LzgxW60XtGEeMY2R7onMQwUKRXJp7Sb96gMUrem8oMdSZDpXPG8yRpi3I5niGrUNC+dB92EBPGUCXOpo+kgtduRKrE0uxyg55mZY07m2M2yGY7JnBMIdyGzNHP60cylHjo3uh4Q4L3fUBvuYXtpsv7pVCAB/Ye8MkJVbAYEosag9F6tKhodtuCrYl6sZL7MGiEZm+13yDYjZU84YJASwHawNtbKGnaZaWz7WafPdQaR7TK/d7iVVdS/UwWixgzDxvELEXO7vQJ6gE+VtAQxr5YOz9qtMMlTAIvXRM0d19w6hZ7Khyg9cviSYJA7drS2djBni+5uzHX7ISGXUVmY=
