language: node_js
node_js:
- '12'
dist: trusty
sudo: required
env:
  global:
    secure: rXBK+5PiYEhpUYucwznsrkAcfdQ8HYrAMdGpz4sZCLTkcGUDfEGiCarUWt0RUPgyGzD6RJT70Ob9SkE8fNIOhKitmRW6lW6dMpyvkt2NEbDbJzjBBa3Kg1v82BPrpLmzM8tPXhl3FHB692OjXnpXhThgbwbnqrfTu/0++HltwsV/1CBhhMZV0pPtAlCXo4E1iaqXxF49lcc7lB56/iSQbALgpPjWEPrTAusVgxKVY46UV1iv/gqYlYwo6qy2vrQRK6gTTWsG8OTaXGPoaFoW+Qgj6reYut3boU3RBfFkQ9XhGvKVOnSRakOujjZbZHmHSfFaYLp8NgCSiowoSBdci3gOgHniuLxPpvbcex9csRysidE32GJPBkfTTAa7AakyVkONSXLd5mj+f3hx+kB3cUiDCMwa3CCOd0SLKlxtAI10jElc4GTyWmCBd/BYLajtgPApjLMod9FGTotq8Snxw+VZPKXJwhmahfxtbkA5d4joHAGJHAyMj/RGW7wv7tkYja7OUWp9ldeVZJzw0YxHiYfbEJ+je+2hxiQTUpoxjFf9gYGd13Pp6iN2OpyVAc/iyR7xnqSQ2q/quYMHkxpekjwT3eqr5roVJFVk4PWfnt9AzytqF6fP3vqg6LR1yBdA01Q3oK6TVjw3+xJGQB2MC9CO7RNndCyHOLwX4rynk3w=
addons:
  chrome: stable
  sonarcloud:
    organization: jorgerambla
    token:
      secure: "$SONAR_TOKEN"
before_script:
- npm install -g --silent @angular/cli@8.3.20
script:
- ng lint
#- sonar-scanner
