language: node_js
node_js:
- '12'
dist: trusty
sudo: required
env:
  global:
    secure: 2d5Ru9uKt5iRur2b/CuDWgME7zYWrGIM7bJWehfklxJ0kpywWSZOYOZ6/8ORI8D2TtptWork0njZIpKG0U74S9DtuJuSDs6/FVfsdVVtH+NiKSn3iH7pvJab1JJ/eWqWZg17v0MtjTRXZkoVQnPOgR/8smX/HiP2hES5AAsUsvc14v72ZLf/FRAH6CNAfMhRP7WlxX25fqdiQ+R3wsFqgd0ykFsR+1T8+/dYWHWm55FW0eQfkn1UjtHk0xJ+0wd5QQ0iAxeFQNsyYBaQ6RMdPJALLWIdxdt/9QCWP+Td7NdlS0UMjb2ib7ASQg0ZKj1ODkd8BkQ3htWjvuC9q1MAJLxPpspSYfIypXavq4eq3XPY5vA9Z9W2T0wV8biM07wDl3XMchk9epzOBt3GE1PwM0B5YgB6D5pk8LYZJ2c+O5o6gHaMAR4wgW4Dc+dw5GbACC9IqaUDViYAtIFkA4wkTasPjV/7Fz3rFqpg2S1KEAm5UPbnHIZPh77CVae9ZaoU2qHiV4B3I417XdeNhY6Hp2MP3oa76O/1mDjwjncEDSJa3nvloRDz4Ws6TTx9PYf7A7x3T/MN7/hR2S7pr6K4LmXrOXwYs+YJhpsrFxh6WryYgy44QeOoj2wroZXgHK+uhFm5nswYcLSq0dHHXi+b11P9iLuQkQaMavaUkG2YpV0=
addons:
  chrome: stable
  sonarcloud:
    organization: jorgerambla
    token: "$SONAR_TOKEN"
before_script:
- npm install -g --silent @angular/cli@8.3.20
script:
- ng lint
- "./build.sh"
- sonar-scanner
